import { SchemeCategory, EmploymentType, IncomeRange } from '../types';

export const INDIAN_STATES = [
  'All India',
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Jammu and Kashmir',
  'Ladakh',
  'Lakshadweep',
  'Puducherry',
];

export const POPULAR_DISTRICTS: Record<string, string[]> = {
  "Andhra Pradesh": [
      "Alluri Sitharama Raju",
      "Anakapalli",
      "Ananthapuramu",
      "Annamayya",
      "Bapatla",
      "Chittoor",
      "Dr. B.R. Ambedkar Konaseema",
      "Eluru",
      "Guntur",
      "Kakinada",
      "Krishna",
      "Kurnool",
      "Nandyal",
      "NTR",
      "Palnadu",
      "Parvathipuram Manyam",
      "Prakasam",
      "Sri Potti Sriramulu Nellore",
      "Sri Sathya Sai",
      "Srikakulam",
      "Tirupati",
      "Visakhapatnam",
      "Vizianagaram",
      "West Godavari",
      "YSR Kadapa",
      "Others"
  ],
  "Arunachal Pradesh": [
      "Anjaw",
      "Changlang",
      "Dibang Valley",
      "East Kameng",
      "East Siang",
      "Kamle",
      "Kra Daadi",
      "Kurung Kumey",
      "Lepa Rada",
      "Lohit",
      "Longding",
      "Lower Dibang Valley",
      "Lower Siang",
      "Lower Subansiri",
      "Namsai",
      "Pakke Kessang",
      "Papum Pare",
      "Shi Yomi",
      "Siang",
      "Tawang",
      "Tirap",
      "Upper Siang",
      "Upper Subansiri",
      "West Kameng",
      "West Siang",
      "Others"
  ],
  "Assam": [
      "Bajali",
      "Baksa",
      "Barpeta",
      "Biswanath",
      "Bongaigaon",
      "Cachar",
      "Charaideo",
      "Chirang",
      "Darrang",
      "Dhemaji",
      "Dhubri",
      "Dibrugarh",
      "Dima Hasao",
      "Goalpara",
      "Golaghat",
      "Hailakandi",
      "Hojai",
      "Jorhat",
      "Kamrup",
      "Kamrup Metropolitan",
      "Karbi Anglong",
      "Karimganj",
      "Kokrajhar",
      "Lakhimpur",
      "Majuli",
      "Morigaon",
      "Nagaon",
      "Nalbari",
      "Sivasagar",
      "Sonitpur",
      "South Salmara-Mankachar",
      "Tinsukia",
      "Udalguri",
      "West Karbi Anglong",
      "Others"
  ],
  "Bihar": [
      "Araria",
      "Arwal",
      "Aurangabad",
      "Banka",
      "Begusarai",
      "Bhagalpur",
      "Bhojpur",
      "Buxar",
      "Darbhanga",
      "East Champaran",
      "Gaya",
      "Gopalganj",
      "Jamui",
      "Jehanabad",
      "Kaimur",
      "Katihar",
      "Khagaria",
      "Kishanganj",
      "Lakhisarai",
      "Madhepura",
      "Madhubani",
      "Munger",
      "Muzaffarpur",
      "Nalanda",
      "Nawada",
      "Patna",
      "Purnia",
      "Rohtas",
      "Saharsa",
      "Samastipur",
      "Saran",
      "Sheikhpura",
      "Sheohar",
      "Sitamarhi",
      "Siwan",
      "Supaul",
      "Vaishali",
      "West Champaran",
      "Others"
  ],
  "Chhattisgarh": [
      "Balod",
      "Baloda Bazar-Bhatapara",
      "Balrampur-Ramanujganj",
      "Bastar",
      "Bemetara",
      "Bijapur",
      "Bilaspur",
      "Dantewada",
      "Dhamtari",
      "Durg",
      "Gariaband",
      "Gaurela-Pendra-Marwahi",
      "Janjgir-Champa",
      "Jashpur",
      "Kanker",
      "Kabirdham",
      "Kondagaon",
      "Korba",
      "Koriya",
      "Mahasamund",
      "Manendragarh-Chirmiri-Bharatpur",
      "Mohla-Manpur-Ambagarh Chowki",
      "Mungeli",
      "Narayanpur",
      "Raigarh",
      "Raipur",
      "Rajnandgaon",
      "Sukma",
      "Surajpur",
      "Surguja",
      "Sakti",
      "Sarangarh-Bilaigarh",
      "Others"
  ],
  "Goa": [
      "North Goa",
      "South Goa",
      "Others"
  ],
  "Gujarat": [
      "Ahmedabad",
      "Amreli",
      "Anand",
      "Aravalli",
      "Banaskantha",
      "Bharuch",
      "Bhavnagar",
      "Botad",
      "Chhota Udaipur",
      "Dahod",
      "Dang",
      "Devbhumi Dwarka",
      "Gandhinagar",
      "Gir Somnath",
      "Jamnagar",
      "Junagadh",
      "Kheda",
      "Kutch",
      "Mahisagar",
      "Mehsana",
      "Morbi",
      "Narmada",
      "Navsari",
      "Panchmahal",
      "Patan",
      "Porbandar",
      "Rajkot",
      "Sabarkantha",
      "Surat",
      "Surendranagar",
      "Tapi",
      "Vadodara",
      "Valsad",
      "Others"
  ],
  "Haryana": [
      "Ambala",
      "Bhiwani",
      "Charkhi Dadri",
      "Faridabad",
      "Fatehabad",
      "Gurugram",
      "Hisar",
      "Jhajjar",
      "Jind",
      "Kaithal",
      "Karnal",
      "Kurukshetra",
      "Mahendragarh",
      "Nuh",
      "Palwal",
      "Panchkula",
      "Panipat",
      "Rewari",
      "Rohtak",
      "Sirsa",
      "Sonipat",
      "Yamunanagar",
      "Others"
  ],
  "Himachal Pradesh": [
      "Bilaspur",
      "Chamba",
      "Hamirpur",
      "Kangra",
      "Kinnaur",
      "Kullu",
      "Lahaul and Spiti",
      "Mandi",
      "Shimla",
      "Sirmaur",
      "Solan",
      "Una",
      "Others"
  ],
  "Jharkhand": [
      "Bokaro",
      "Chatra",
      "Deoghar",
      "Dhanbad",
      "Dumka",
      "East Singhbhum",
      "Garhwa",
      "Giridih",
      "Godda",
      "Gumla",
      "Hazaribagh",
      "Jamtara",
      "Khunti",
      "Koderma",
      "Latehar",
      "Lohardaga",
      "Pakur",
      "Palamu",
      "Ramgarh",
      "Ranchi",
      "Sahibganj",
      "Seraikela Kharsawan",
      "Simdega",
      "West Singhbhum",
      "Others"
  ],
  "Karnataka": [
      "Bagalkot",
      "Ballari",
      "Belagavi",
      "Bengaluru Rural",
      "Bengaluru Urban",
      "Bidar",
      "Chamarajanagar",
      "Chikkaballapur",
      "Chikkamagaluru",
      "Chitradurga",
      "Dakshina Kannada",
      "Davanagere",
      "Dharwad",
      "Gadag",
      "Hassan",
      "Haveri",
      "Kalaburagi",
      "Kodagu",
      "Kolar",
      "Koppal",
      "Mandya",
      "Mysuru",
      "Raichur",
      "Ramanagara",
      "Shivamogga",
      "Tumakuru",
      "Udupi",
      "Uttara Kannada",
      "Vijayanagara",
      "Vijayapura",
      "Yadgir",
      "Others"
  ],
  "Kerala": [
      "Alappuzha",
      "Ernakulam",
      "Idukki",
      "Kannur",
      "Kasaragod",
      "Kollam",
      "Kottayam",
      "Kozhikode",
      "Malappuram",
      "Palakkad",
      "Pathanamthitta",
      "Thiruvananthapuram",
      "Trissur",
      "Wayanad",
      "Others"
  ],
  "Madhya Pradesh": [
      "Agar Malwa",
      "Alirajpur",
      "Anuppur",
      "Ashoknagar",
      "Balaghat",
      "Barwani",
      "Betul",
      "Bhind",
      "Bhopal",
      "Burhanpur",
      "Chhatarpur",
      "Chhindwara",
      "Damoh",
      "Datia",
      "Dewas",
      "Dhar",
      "Dindori",
      "Guna",
      "Gwalior",
      "Harda",
      "Hoshangabad (Narmadapuram)",
      "Indore",
      "Jabalpur",
      "Jhabua",
      "Katni",
      "Khandwa",
      "Khargone",
      "Mandla",
      "Mandsaur",
      "Morena",
      "Narsinghpur",
      "Neemuch",
      "Niwari",
      "Panna",
      "Raisen",
      "Rajgarh",
      "Ratlam",
      "Rewa",
      "Sagar",
      "Satna",
      "Sehore",
      "Seoni",
      "Shahdol",
      "Shajapur",
      "Sheopur",
      "Shivpuri",
      "Sidhi",
      "Singrauli",
      "Tikamgarh",
      "Ujjain",
      "Umaria",
      "Vidisha",
      "Mauganj",
      "Maihar",
      "Chachoura",
      "Others"
  ],
  "Maharashtra": [
      "Ahmednagar",
      "Akola",
      "Amravati",
      "Chhatrapati Sambhajinagar (Aurangabad)",
      "Beed",
      "Bhandara",
      "Buldhana",
      "Chandrapur",
      "Dharashiv (Osmanabad)",
      "Dhule",
      "Gadchiroli",
      "Gondia",
      "Hingoli",
      "Jalgaon",
      "Jalna",
      "Kolhapur",
      "Latur",
      "Mumbai City",
      "Mumbai Suburban",
      "Nagpur",
      "Nanded",
      "Nandurbar",
      "Nashik",
      "Navi Mumbai",
      "Palghar",
      "Parbhani",
      "Pune",
      "Raigad",
      "Ratnagiri",
      "Sangli",
      "Satara",
      "Sindhudurg",
      "Solapur",
      "Thane",
      "Wardha",
      "Washim",
      "Yavatmal",
      "Others"
  ],
  "Manipur": [
      "Bishnupur",
      "Chandel",
      "Churachandpur",
      "Imphal East",
      "Imphal West",
      "Jiribam",
      "Kakching",
      "Kamjong",
      "Kangpokpi",
      "Noney",
      "Pherzawl",
      "Senapati",
      "Tamenglong",
      "Tengnoupal",
      "Thoubal",
      "Ukhrul",
      "Others"
  ],
  "Meghalaya": [
      "East Garo Hills",
      "East Jaintia Hills",
      "East Khasi Hills",
      "Eastern West Khasi Hills",
      "North Garo Hills",
      "Ri Bhoi",
      "South Garo Hills",
      "South West Garo Hills",
      "South West Khasi Hills",
      "West Garo Hills",
      "West Jaintia Hills",
      "West Khasi Hills",
      "Others"
  ],
  "Mizoram": [
      "Aizawl",
      "Champhai",
      "Hnahthial",
      "Khawzawl",
      "Kolasib",
      "Lawngtlai",
      "Lunglei",
      "Mamit",
      "Saiha",
      "Saitual",
      "Serchhip",
      "Others"
  ],
  "Nagaland": [
      "Chümoukedima",
      "Dimapur",
      "Kiphire",
      "Kohima",
      "Longleng",
      "Mokokchung",
      "Mon",
      "Niuland",
      "Noklak",
      "Peren",
      "Phek",
      "Shamator",
      "Tseminyu",
      "Tuensang",
      "Wokha",
      "Zunheboto",
      "Others"
  ],
  "Odisha": [
      "Angul",
      "Balangir",
      "Balasore",
      "Bargarh",
      "Bhadrak",
      "Boudh",
      "Cuttack",
      "Deogarh",
      "Dhenkanal",
      "Gajapati",
      "Ganjam",
      "Jagatsinghpur",
      "Jajpur",
      "Jharsuguda",
      "Kalahandi",
      "Kandhamal",
      "Kendrapara",
      "Kendujhar",
      "Khordha",
      "Koraput",
      "Malkangiri",
      "Mayurbhanj",
      "Nabarangpur",
      "Nayagarh",
      "Nuapada",
      "Puril",
      "Rayagada",
      "Sambalpur",
      "Subarnapur",
      "Sundargarh",
      "Others"
  ],
  "Punjab": [
      "Amritsar",
      "Barnala",
      "Bathinda",
      "Faridkot",
      "Fatehgarh Sahib",
      "Fazilka",
      "Firozpur",
      "Gurdaspur",
      "Hoshiarpur",
      "Jalandhar",
      "Kapurthala",
      "Ludhiana",
      "Malerkotla",
      "Mansa",
      "Moga",
      "Muktsar",
      "Pathankot",
      "Patiala",
      "Rupnagar",
      "Sahibzada Ajit Singh Nagar (Mohali)",
      "Sangrur",
      "Shahid Bhagat Singh Nagar",
      "Tarn Taran",
      "Others"
  ],
  "Rajasthan": [
      "Ajmer",
      "Alwar",
      "Anupgarh",
      "Balotra",
      "Banswara",
      "Baran",
      "Barmer",
      "Beawar",
      "Bharatpur",
      "Bhilwara",
      "Bikaner",
      "Bundi",
      "Chittorgarh",
      "Churu",
      "Dausa",
      "Deeg",
      "Didwana-Kuchaman",
      "Dholpur",
      "Dudu",
      "Dungarpur",
      "Gangapur City",
      "Hanumangarh",
      "Jaipur",
      "Jaipur Rural",
      "Jaisalmer",
      "Jalore",
      "Jhalawar",
      "Jhunjhunu",
      "Jodhpur",
      "Jodhpur Rural",
      "Karauli",
      "Kekri",
      "Kota",
      "Kotputli-Behror",
      "Nagaur",
      "Neem Ka Thana",
      "Pali",
      "Phalodi",
      "Pratapgarh",
      "Rajsamand",
      "Salumbar",
      "Sanchore",
      "Sawai Madhopur",
      "Shahpura",
      "Sikar",
      "Sirohi",
      "Sri Ganganagar",
      "Tonk",
      "Udaipur",
      "Others"
  ],
  "Sikkim": [
      "Gangtok",
      "Mangan",
      "Nanchi",
      "Gyalshing",
      "Pakyong",
      "Soreng",
      "Others"
  ],
  "Tamil Nadu": [
      "Ariyalur",
      "Chengalpattu",
      "Chennai",
      "Coimbatore",
      "Cuddalore",
      "Dharmapuri",
      "Dindigul",
      "Erode",
      "Kallakurichi",
      "Kanchipuram",
      "Kanyakumari",
      "Karur",
      "Krishnagiri",
      "Madurai",
      "Mayiladuthurai",
      "Nagapattinam",
      "Namakkal",
      "Nilgiris",
      "Perambalur",
      "Pudukkottai",
      "Ramanathapuram",
      "Ranipet",
      "Salem",
      "Sivaganga",
      "Tenkasi",
      "Thanjavur",
      "Theni",
      "Thoothukudi",
      "Tiruchirappalli",
      "Tirunelveli",
      "Tirupathur",
      "Tiruppur",
      "Tiruvallur",
      "Tiruvannamalai",
      "Tiruvarur",
      "Vellore",
      "Viluppuram",
      "Virudhunagar",
      "Others"
  ],
  "Telangana": [
      "Adilabad",
      "Bhadradri Kothagudem",
      "Hanamkonda",
      "Hyderabad",
      "Jagtial",
      "Jangaon",
      "Jayashankar Bhupalpally",
      "Jogulamba Gadwal",
      "Kamareddy",
      "Karimnagar",
      "Khammam",
      "Kumuram Bheem Asifabad",
      "Mahabubabad",
      "Mahabubnagar",
      "Mancherial",
      "Medak",
      "Medchal-Malkajgiri",
      "Mulugu",
      "Nagarkurnool",
      "Nalgonda",
      "Narayanpet",
      "Nirmal",
      "Nizamabad",
      "Peddapalli",
      "Rajanna Sircilla",
      "Rangareddy",
      "Sangareddy",
      "Siddipet",
      "Suryapet",
      "Vikarabad",
      "Wanaparthy",
      "Warangal",
      "Yadadri Bhuvanagiri",
      "Others"
  ],
  "Tripura": [
      "Dhalai",
      "Gomati",
      "Khowai",
      "North Tripura",
      "Sepahijala",
      "South Tripura",
      "Unakoti",
      "West Tripura",
      "Others"
  ],
  "Uttar Pradesh": [
      "Agra",
      "Aligarh",
      "Ambedkar Nagar",
      "Amethi",
      "Amroha",
      "Auraiya",
      "Ayodhya",
      "Azamgarh",
      "Baghpat",
      "Bahraich",
      "Ballia",
      "Balrampur",
      "Banda",
      "Barabanki",
      "Bareilly",
      "Basti",
      "Bhadohi",
      "Bijnor",
      "Budaun",
      "Bulandshahr",
      "Chandauli",
      "Chitrakoot",
      "Deoria",
      "Etah",
      "Etawah",
      "Farrukhabad",
      "Fatehpur",
      "Firozabad",
      "Gautam Buddha Nagar",
      "Ghaziabad",
      "Ghazipur",
      "Gonda",
      "Gorakhpur",
      "Hamirpur",
      "Hapur",
      "Hardoi",
      "Hathras",
      "Jalaun",
      "Jaunpur",
      "Jhansi",
      "Kannauj",
      "Kanpur Dehat",
      "Kanpur Nagar",
      "Kasganj",
      "Kaushambi",
      "Kushinagar",
      "Lakhimpur Kheri",
      "Lalitpur",
      "Lucknow",
      "Maharajganj",
      "Mahoba",
      "Mainpuri",
      "Mathura",
      "Mau",
      "Meerut",
      "Mirzapur",
      "Moradabad",
      "Muzaffarnagar",
      "Pilibhit",
      "Pratapgarh",
      "Prayagraj",
      "Raebareli",
      "Rampur",
      "Saharanpur",
      "Sambhal",
      "Sant Kabir Nagar",
      "Shahjahanpur",
      "Shamli",
      "Shravasti",
      "Siddharthnagar",
      "Sitapur",
      "Sonbhadra",
      "Sultanpur",
      "Unnao",
      "Varanasi",
      "Others"
  ],
  "Uttarakhand": [
      "Almora",
      "Bageshwar",
      "Chamoli",
      "Champawat",
      "Dehradun",
      "Haridwar",
      "Nainital",
      "Pauri Garhwal",
      "Pithoragarh",
      "Rudraprayag",
      "Tehri Garhwal",
      "Udham Singh Nagar",
      "Uttarkashi",
      "Others"
  ],
  "West Bengal": [
      "Alipurduar",
      "Bankura",
      "Birbhum",
      "Cooch Behar",
      "Dakshin Dinajpur",
      "Darjeeling",
      "Hooghly",
      "Howrah",
      "Jalpaiguri",
      "Jhargram",
      "Kalimpong",
      "Kolkata",
      "Malda",
      "Murshidabad",
      "Nadia",
      "North 24 Parganas",
      "Paschim Bardhaman",
      "Paschim Medinipur",
      "Purba Bardhaman",
      "Purba Medinipur",
      "Purulia",
      "South 24 Parganas",
      "Uttar Dinajpur",
      "Others"
  ],
  "Andaman and Nicobar Islands": [
      "Nicobar",
      "North and Middle Andaman",
      "South Andaman",
      "Others"
  ],
  "Chandigarh": [
      "Chandigarh",
      "Others"
  ],
  "Dadra and Nagar Haveli and Daman and Diu": [
      "Dadra and Nagar Haveli",
      "Daman",
      "Diu",
      "Others"
  ],
  "Delhi": [
      "Central Delhi",
      "East Delhi",
      "New Delhi",
      "North Delhi",
      "North East Delhi",
      "North West Delhi",
      "Shahdara",
      "South Delhi",
      "South East Delhi",
      "South West Delhi",
      "West Delhi",
      "Others"
  ],
  "Jammu and Kashmir": [
      "Anantnag",
      "Bandipora",
      "Baramulla",
      "Budgam",
      "Doda",
      "Ganderbal",
      "Jammu",
      "Kathua",
      "Kishtwar",
      "Kulgam",
      "Kupwara",
      "Mandoob",
      "Poonch",
      "Pulwama",
      "Rajouri",
      "Ramban",
      "Reasi",
      "Samba",
      "Shopian",
      "Srinagar",
      "Udhampur",
      "Others"
  ],
  "Ladakh": [
      "Kargil",
      "Leh",
      "Others"
  ],
  "Lakshadweep": [
      "Lakshadweep",
      "Others"
  ],
  "Puducherry": [
      "Karaikal",
      "Mahé",
      "Puducherry",
      "Yanam",
      "Others"
  ],
  // Aliases for backward compatibility with previous naming
  'Delhi (NCT)': [
      "Central Delhi",
      "East Delhi",
      "New Delhi",
      "North Delhi",
      "North East Delhi",
      "North West Delhi",
      "Shahdara",
      "South Delhi",
      "South East Delhi",
      "South West Delhi",
      "West Delhi",
      "Others"
  ],
  'Jammu & Kashmir': [
      "Anantnag",
      "Bandipora",
      "Baramulla",
      "Budgam",
      "Doda",
      "Ganderbal",
      "Jammu",
      "Kathua",
      "Kishtwar",
      "Kulgam",
      "Kupwara",
      "Mandoob",
      "Poonch",
      "Pulwama",
      "Rajouri",
      "Ramban",
      "Reasi",
      "Samba",
      "Shopian",
      "Srinagar",
      "Udhampur",
      "Others"
  ],
};

export const SCHEME_CATEGORIES: SchemeCategory[] = [
  'Education',
  'Agriculture',
  'Employment',
  'Business',
  'Women & Child',
  'Housing',
  'Healthcare',
  'Social Security',
  'Financial Assistance',
  'Skill Development',
];

export const CATEGORIES_WITH_META: { id: SchemeCategory; icon: string; count: number; desc: string }[] = [
  { id: 'Social Security', icon: 'Users', count: 1249, desc: 'Old-age pensions, widow pensions, disability stipends & social welfare' },
  { id: 'Education', icon: 'GraduationCap', count: 816, desc: 'Scholarships, fee waivers, educational loans & research grants' },
  { id: 'Agriculture', icon: 'Sprout', count: 614, desc: 'Income support, crop insurance, solar pumps & farm subsidies' },
  { id: 'Business', icon: 'Briefcase', count: 500, desc: 'Collateral-free loans, MSME subsidies & startup capital' },
  { id: 'Healthcare', icon: 'ShieldPlus', count: 156, desc: 'Cashless treatment cover, health insurance & wellness centers' },
  { id: 'Financial Assistance', icon: 'Coins', count: 100, desc: 'Direct benefit transfers, interest relief & economic aid' },
  { id: 'Skill Development', icon: 'Lightbulb', count: 100, desc: 'Free vocational certifications, industry skilling & toolkits' },
  { id: 'Employment', icon: 'UserCheck', count: 96, desc: 'Apprenticeships, placement linked programs & livelihood missions' },
  { id: 'Women & Child', icon: 'HeartHandshake', count: 73, desc: 'Maternity assistance, girl child savings & self-help support' },
  { id: 'Housing', icon: 'Home', count: 64, desc: 'Pucca house subsidies, interest subvention & urban housing' },
];

export const DEFAULT_CATEGORY_COUNTS: Record<string, number> = {
  'Social Security': 1249,
  'Education': 816,
  'Agriculture': 614,
  'Business': 500,
  'Healthcare': 156,
  'Financial Assistance': 100,
  'Skill Development': 100,
  'Employment': 96,
  'Women & Child': 73,
  'Housing': 64,
  'Sports & Culture': 52,
  'Travel & Tourism': 19,
};

export const EMPLOYMENT_TYPES: EmploymentType[] = [
  'Student',
  'Farmer',
  'Business owner',
  'Employed',
  'Unemployed',
  'Self-employed',
  'Homemaker',
  'Retired',
  'Other',
];

export const INCOME_RANGES: IncomeRange[] = [
  'Below ₹1 lakh',
  '₹1–2.5 lakh',
  '₹2.5–5 lakh',
  '₹5–10 lakh',
  '₹10 lakh+',
  'Prefer not to say',
];

export const AUDIENCE_PERSONAS = [
  {
    id: 'students',
    label: 'Students',
    icon: 'GraduationCap',
    headline: 'Education Grants & Skill Development',
    description: 'Find merit scholarships, post-matric fee waivers, coaching subsidies, and laptop/device distribution programs.',
    keySchemes: ['PM Uchchatar Shiksha Protsahan', 'NSP Central Sector Scheme', 'National Means-cum-Merit'],
    sampleProfile: { age: 20, state: 'Haryana', employmentType: 'Student', incomeRange: '₹1–2.5 lakh' }
  },
  {
    id: 'farmers',
    label: 'Farmers',
    icon: 'Sprout',
    headline: 'Agricultural & Income Support',
    description: 'Discover direct income support, PM-KUSUM solar pumps, PM Fasal Bima crop insurance, and Kisan Credit Cards.',
    keySchemes: ['PM-KISAN Samman Nidhi', 'PM Fasal Bima Yojana', 'PM-KUSUM Solar Pump Scheme'],
    sampleProfile: { age: 42, state: 'Maharashtra', employmentType: 'Farmer', incomeRange: '₹1–2.5 lakh' }
  },
  {
    id: 'entrepreneurs',
    label: 'Entrepreneurs',
    icon: 'Rocket',
    headline: 'MSME & Startup Financial Backing',
    description: 'Access collateral-free loans up to ₹10 Lakh, Stand-Up India funding, and PMEGP capital subsidies up to 35%.',
    keySchemes: ['PM Mudra Yojana (PMMY)', 'Prime Minister Employment Generation (PMEGP)', 'Stand-Up India Scheme'],
    sampleProfile: { age: 29, state: 'Karnataka', employmentType: 'Business owner', incomeRange: '₹2.5–5 lakh' }
  },
  {
    id: 'women',
    label: 'Women',
    icon: 'Heart',
    headline: 'Women Empowerment & Financial Independence',
    description: 'Explore high-interest savings for girl children, maternity assistance, SHG loans, and women-led enterprise grants.',
    keySchemes: ['Sukanya Samriddhi Yojana', 'PM Matru Vandana Yojana', 'Mahila Samman Savings Certificate'],
    sampleProfile: { age: 28, gender: 'female', state: 'Uttar Pradesh', incomeRange: 'Below ₹1 lakh' }
  },
  {
    id: 'jobseekers',
    label: 'Job Seekers',
    icon: 'Briefcase',
    headline: 'Vocational Training & Employment',
    description: 'Find free certified vocational skilling, national apprenticeship stipends, and placement-linked livelihood training.',
    keySchemes: ['PM Kaushal Vikas Yojana 4.0', 'National Apprenticeship Promotion Scheme', 'Deen Dayal Upadhyaya GKY'],
    sampleProfile: { age: 23, employmentType: 'Unemployed', state: 'Rajasthan', incomeRange: 'Below ₹1 lakh' }
  },
  {
    id: 'families',
    label: 'Families',
    icon: 'Home',
    headline: 'Welfare, Housing & Healthcare',
    description: 'Get ₹5 Lakh annual cashless healthcare for the family, pucca house construction subsidies, and subsidized food security.',
    keySchemes: ['Ayushman Bharat PM-JAY', 'PM Awas Yojana (Gramin & Urban)', 'PM Ujjwala Yojana'],
    sampleProfile: { age: 36, hasBPLCard: true, state: 'Madhya Pradesh', incomeRange: 'Below ₹1 lakh' }
  },
  {
    id: 'seniors',
    label: 'Senior Citizens',
    icon: 'Shield',
    headline: 'Pensions & Social Security',
    description: 'Secure guaranteed monthly pensions, subsidized medical checkups, and old-age social security stipends.',
    keySchemes: ['Indira Gandhi National Old Age Pension', 'Atal Pension Yojana', 'PM Vaya Vandana Yojana'],
    sampleProfile: { age: 64, employmentType: 'Retired', state: 'Delhi', incomeRange: '₹1–2.5 lakh' }
  },
];

export const STATS_DATA = [
  { value: '3000+', label: 'Schemes Indexed', note: 'Central & State databases' },
  { value: '50+', label: 'Government Depts', note: 'Ministries & Directorates' },
  { value: '24/7', label: 'Guidance Engine', note: 'Transparent & explainable' },
];


export const TRUST_PILLARS = [
  {
    icon: 'CheckCircle2',
    title: 'Verified Information',
    description: 'Every scheme lists the managing ministry, official application URL, and last verified timestamp.',
  },
  {
    icon: 'Lock',
    title: 'Secure & Private',
    description: 'Your profile data is stored locally in your browser. We never sell or share your personal details.',
  },
  {
    icon: 'Clock',
    title: 'Save Time & Effort',
    description: 'No more searching through dozens of disconnected gazettes and portals. One unified compass.',
  },
  {
    icon: 'Compass',
    title: 'Explainable Guidance',
    description: 'We don’t just show matching schemes — we explain exactly which criteria you satisfy.',
  },
];

export const HOW_IT_WORKS_STEPS = [
  {
    step: '01',
    title: 'Tell Us About You',
    description: 'Answer a few simple questions regarding your location, occupation, and basic background without any paperwork.',
    highlight: 'No scheme knowledge needed',
    icon: 'UserCheck',
  },
  {
    step: '02',
    title: 'Discover Relevant Schemes',
    description: 'Our rule-based matching engine filters thousands of eligibility conditions to find schemes that fit your exact profile.',
    highlight: 'Instant multi-criteria matching',
    icon: 'Cpu',
  },
  {
    step: '03',
    title: 'Understand Your Options',
    description: 'Read plain-English summaries, exact benefit values, required document checklists, and match reasoning.',
    highlight: 'Plain language, no jargon',
    icon: 'FileText',
  },
  {
    step: '04',
    title: 'Apply With Confidence',
    description: 'Follow our step-by-step checklist and proceed safely to the verified official government portal (.gov.in / .nic.in).',
    highlight: 'Safe exit to official portal',
    icon: 'ExternalLink',
  },
];

export const FAQ_LIST = [
  {
    q: 'Is SchemeNavigator an official government website?',
    a: 'No. SchemeNavigator is an independent, citizen-first discovery and guidance platform. We act as a navigational compass to help citizens find and understand schemes, but all final applications, verifications, and approvals occur on official government portals (e.g., myscheme.gov.in, nsp.gov.in, pmkisan.gov.in).',
  },
  {
    q: 'Does SchemeNavigator charge any fees for recommendations?',
    a: 'Never. SchemeNavigator is completely free for all citizens. Government schemes never require fees for discovery, and you should beware of fraudulent agents.',
  },
  {
    q: 'How does the Match Score work?',
    a: 'Our matching algorithm evaluates your profile (age, income range, state, occupation, category) against official eligibility parameters and assigns a compatibility percentage. It is an informational indicator, not a government approval.',
  },
  {
    q: 'Is my personal profile information safe?',
    a: 'Yes. We follow strict data minimization principles. Your profile inputs are processed locally in your browser to generate matching results. We do not ask for sensitive personal identification cards like full Aadhaar numbers, pancard, income and caste certificates, etc.',
  },

  {
    q: 'What if I find a scheme that has recently updated guidelines?',
    a: 'We list the last verified date and provide direct links to the official ministry portal where the latest gazettes and operational guidelines are maintained.',
  },
];

export const SAMPLE_AI_PROMPTS = [
  'I am a 20-year-old college student from Haryana with a family income of ₹1.5 Lakh. What scholarships apply to me?',
  'I am a small farmer in Maharashtra with 2 acres of land. What income and equipment subsidies are available?',
  'I am a woman looking to start a small food processing business. Are there collateral-free loans or grants?',
  'What welfare schemes provide free healthcare cover up to ₹5 Lakh for low-income families?',
  'Are there government schemes offering free vocational training with stipend for 12th pass students?',
];
